### ISSUE TITLE
unix build of the 8.5 branch fails to build on Mac OS X with LTO (-flto)

### ISSUE THREAD

**Issue by RJVB** [tcltk/tcl#2]
Building the generic Unix flavour of Tcl 8.5 on OS X (as done for instance by MacPorts to obtain the interpreter driving the entire build/packaging system) fails when using Link-Time Optimisation (-flto compiler/linker option).

When this option is used, the Tcl build system erroneously detects the presence of the pthread_attr_get_np() function which exists only on Linux; as a result, compilation fails on `#include <pthread_np.h>` .

This issue boils down to a failing conftest.c programme generated by the configure script (and I think specified by the tcl.m4 file). In essence, this test does

```
main () {
    char pthread_attr_get_np();
    char (*f)() = pthread_attr_get_np;
    return f != pthread_attr_get_np;
}
```

Semantically, the actual value of `f` is moot in the boolean expression, which in fact can only evaluate to false. With LTO activated, clang recognises this fact, suppresses the reference to the actual function and as a result does not fail to link when that function isn't available.
Adding a call to a function with side-effects (unknown to the linker, such as `printf("%p", pthread_attr_get_np);` restores the expected behaviour (i.e. the link step fails, and thus the test also).

**Comment by sebres** [comment]
Thanks for reporting of issue.
This is a mirror of tcl core. Official repository and ticket system could be found in http://core.tcl.tk/tcl/
Please open a ticket there.

Thus closed now.

**Comment by RJVB** [comment]
On Sunday October 11 2015 23:46:04 Serg G. Brester wrote:
>Thanks for reporting of issue.
>This is a mirror of tcl core. Official repository and ticket system could be found in http://core.tcl.tk/tcl/
>Please open a ticket there.

I did look there, but I either overlooked the thing or am searching for the wrong name.
Incidentally I also have an account here already ...

R.

**Comment by sebres** [comment]
BTW. You don't need an acccount in tcl-core to post a ticket.

**Comment by eprozium** [comment]
Than disable the issues from this GitHub mirror (and the WIKI too).
